name: MedeX CI

on:
  push:
    branches: [ feature/package-v0.1.0 ]
  pull_request:
    branches: [ feature/package-v0.1.0 ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .
          pip install pytest

      - name: Run tests (package only)
        run: pytest

